### ISSUE TITLE
how store 3D models in the library?

### ISSUE THREAD

**Issue by rat** [arthurbenemann/open-components#3]
I always had a question about Altium. When I import a 3D model (.step file) I need to keep the original .step file or can I remove it?

I noticed that in your library there are models with 3D representation, but the .step files are not in the repository, so I was left with doubts.

**Comment by ARNik** [comment]
Altium inbuilds step model into footprint.
You do not need to keep the original .step file.

**Comment by rat** [comment]
Thanks for the info
